import { baseLayout, esc, rows } from "./base-layout";
import type { LeadNotificationInput } from "../types";
const labels: Record<string,string> = { contact:"Message de contact", quote:"Demande de devis", printing:"Demande impression", "logo-brief":"Brief logo", "free-tool":"Lead outil gratuit", newsletter:"Inscription newsletter", cv:"CV généré", "business-card":"Carte de visite générée", test:"Test SMTP" };
export function internalTemplate(input: LeadNotificationInput) {
  const { lead, metadata = {} } = input; const label = labels[input.type] || input.type;
  const table = rows([["Date", new Date().toLocaleString("fr-FR", { timeZone:"Europe/Paris" })],["Nom",lead.name],["Email",lead.email],["Téléphone",lead.phone],["Entreprise",lead.company],["Service",lead.service],["Budget",lead.budget],["Délai",lead.deadline],["Prix estimé",lead.estimatedPrice],["Outil",lead.toolName],["Message",lead.message],["Détails",lead.details],["Page source",metadata.sourceUrl],["UTM source",metadata.utmSource],["UTM medium",metadata.utmMedium],["UTM campagne",metadata.utmCampaign],["Localisation",[metadata.city,metadata.country].filter(Boolean).join(", ")]]);
  const files = (lead.uploadedFiles || []).map((f) => `<li><a href="${esc(f.url)}">${esc(f.name)}</a></li>`).join("");
  const cta = [{label:"Ouvrir dans le dashboard",href:metadata.dashboardUrl || `${process.env.SITE_URL || "https://art-visions.fr"}/admin/emails`}]; if (metadata.quoteUrl) cta.push({label:"Voir le devis",href:metadata.quoteUrl}); if (metadata.filesUrl) cta.push({label:"Voir les fichiers",href:metadata.filesUrl}); if (lead.email) cta.unshift({label:"Répondre au client",href:`mailto:${lead.email}`});
  return baseLayout({ preheader:`${label} — ${lead.name || lead.email || "nouveau lead"}`, title:`Nouveau : ${label}`, badge:label, body:`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #EDEAF5;border-radius:10px">${table}</table>${files ? `<h2 style="font-size:16px">Fichiers</h2><ul>${files}</ul>`:""}`, cta });
}
export function internalText(input: LeadNotificationInput) { const l=input.lead,m=input.metadata||{}; return [`Nouvelle notification Art Vision : ${input.type}`,`Nom: ${l.name||"—"}`,`Email: ${l.email||"—"}`,`Téléphone: ${l.phone||"—"}`,`Entreprise: ${l.company||"—"}`,`Service: ${l.service||"—"}`,`Budget: ${l.budget||"—"}`,`Délai: ${l.deadline||"—"}`,`Message: ${l.message||"—"}`,`Détails: ${JSON.stringify(l.details||{})}`,`Source: ${m.sourceUrl||"—"}`].join("\n"); }