import "server-only";
import prisma from "@/lib/prisma";
import { queueEmail } from "./send-email";
import { internalTemplate, internalText } from "./templates/internal-notification";
import { clientTemplate, clientText } from "./templates/client-confirmation";
import type { LeadNotificationInput, LeadType } from "./types";
const subjects:Record<LeadType,string>={contact:"Nouveau message de contact",quote:"Nouvelle demande de devis",printing:"Nouvelle demande impression","logo-brief":"Nouveau brief logo","free-tool":"Nouveau lead outil gratuit",newsletter:"Nouvelle inscription newsletter",cv:"Nouveau CV généré","business-card":"Nouvelle carte de visite générée",test:"Test e-mail SMTP"};
const clientSubjects:Record<LeadType,string>={contact:"Nous avons bien reçu votre message — Art Vision",quote:"Votre demande de devis est bien reçue — Art Vision",printing:"Votre demande d’impression est bien reçue — Art Vision","logo-brief":"Votre brief logo est bien reçu — Art Vision","free-tool":"Votre demande est bien reçue — Art Vision",newsletter:"Votre inscription est confirmée — Art Vision",cv:"Votre création a bien été enregistrée — Art Vision","business-card":"Votre création a bien été enregistrée — Art Vision",test:"Test e-mail Art Vision"};
function list(v:string|undefined){try{const p=JSON.parse(v||"[]");return Array.isArray(p)?p.filter((x)=>typeof x==="string"):[]}catch{return[]}}
export async function sendLeadNotification(input:LeadNotificationInput){const settings=await prisma.emailSettings.upsert({where:{id:"default"},update:{},create:{id:"default",primaryNotificationEmail:process.env.CONTACT_NOTIFICATION_EMAIL||"contact@art-visions.fr",senderName:process.env.MAIL_FROM_NAME||"Art Vision",senderEmail:process.env.MAIL_FROM_EMAIL||"contact@art-visions.fr"}}); const enabled=list(settings.enabledTypes); if(enabled.length&& !enabled.includes(input.type)) return {skipped:true}; const display=input.lead.name||input.lead.toolName||input.lead.email||"Nouveau lead"; const recipients=[settings.primaryNotificationEmail,...list(settings.additionalRecipients)]; const internalSubject=`[Art Vision] ${subjects[input.type]} — ${display}`; const internal=await queueEmail({type:`${input.type}:internal`,relatedEntityType:input.relatedEntityType,relatedEntityId:input.relatedEntityId,payload:{to:recipients,subject:internalSubject,html:internalTemplate(input),text:internalText(input),replyTo:settings.replyToVisitor?input.lead.email:undefined}}); let client=null; if(input.lead.email&&settings.clientConfirmationEnabled&&input.sendClientConfirmation!==false){client=await queueEmail({type:`${input.type}:client`,relatedEntityType:input.relatedEntityType,relatedEntityId:input.relatedEntityId,payload:{to:[input.lead.email],subject:clientSubjects[input.type],html:clientTemplate(input),text:clientText(input)}})} return {internal,client};}